[workspace]
resolver = "2"
members = [
  "opendrive_kit_py",
  "opendrive_kit_core",
  "opendrive_kit_quick_xml_reader",
  "opendrive_kit_transform"
]

[workspace.package]
name = "opendrive_kit"
version = "0.1.0"   
license = "MIT"
edition = "2021"
authors = ["Jonas <Jonas.Hablitzel@gmx.de>"]